model_list:
  - model_name: vertex_ai/qwen/qwen3-235b-a22b-instruct-2507-maas
    litellm_params:
      model: vertex_ai/qwen/qwen3-235b-a22b-instruct-2507-maas
      vertex_project: "fx-gen-ai-sandbox"
      vertex_location: "us-south1"
      vertex_credentials: "/app/service_account.json"
  - model_name: vertex_ai/mistral-small-2503
    litellm_params:
      model: vertex_ai/mistral-small-2503
      vertex_project: "fx-gen-ai-sandbox"
      vertex_credentials: "/app/service_account.json"
  - model_name: openai/gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

general_settings:
  store_model_in_db: true
  master_key: os.environ/MASTER_KEY
  database_url: os.environ/PG_DB_URL
  litellm_key_header_name: Authorization

litellm_settings:
  cache: true
  cache_params:
    type: redis
    # With this value supported_call_types: [] the messages will not be cached
    # but redis will be used for rate limiting and other purposes
    supported_call_types: []
    host: redis
    port: 6379
    ttl: 3600
